# Generated by Django 5.1.6 on 2025-05-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0004_alter_product_status_alter_transaction_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('On Cart', 'On Cart'), ('To Pay', 'To Pay'), ('To Ship', 'To Ship'), ('To Recieve', 'To Recieve'), ('Delivered', 'Delivered')], default=None, max_length=255),
        ),
    ]
