# Generated by Django 5.1.6 on 2025-05-08 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_comment_commission'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='people_required',
        ),
        migrations.AddField(
            model_name='commission',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commision', to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Full', 'Full'), ('Completed', 'Compelted'), ('Discontinued', 'Discontinued')], default='Open', max_length=50),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('manpower_required', models.IntegerField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Full', 'Full')], default='Open', max_length=50)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='commissions.commission')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['status', '-manpower_required', 'role'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapplicant', to='user_management.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapplication', to='commissions.job')),
            ],
            options={
                'verbose_name': 'job application',
                'verbose_name_plural': 'job applications',
                'ordering': ['status', 'applied_on'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
