# Generated by Django 5.1.6 on 2025-05-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_remove_commission_people_required_commission_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('A', 'Open'), ('B', 'Full'), ('C', 'Compelted'), ('D', 'Discontinued')], default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('A', 'Open'), ('B', 'Full')], default='A', max_length=50),
        ),
    ]
