# Generated by Django 5.1.6 on 2025-05-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_alter_commission_status_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('A', 'Pending'), ('B', 'Accepted'), ('C', 'Rejected')], default='A', max_length=50),
        ),
    ]
