# Generated by Django 5.1.6 on 2025-05-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('A', 'Open'), ('B', 'Full'), ('C', 'Completed'), ('D', 'Discontinued')], default='A', max_length=50),
        ),
    ]
